# Target to run each script individually
admin:
	flask --app Admin/app run --port 5002

db:
	flask --app DB/app run --port 5001



# Phony targets to avoid conflicts with file names
.PHONY: admin db run-all
